fix the loss of digits after the decimal point
miraclesu/uniswap-sdk-go pull request #3
Opened 2021-06-09 14:46 UTC by hanhan77

2021-06-10 01:56 UTC, miraclesu commented
Thanks @hanhan77! Could you add some tests for this bug?

2021-06-11 02:58 UTC, miraclesu requested changes

2021-06-11 02:58 UTC, miraclesu commented on entities/fraction_test.go
> +		Output [1]string
Output string should be better

2021-06-11 10:42 UTC, emma-chen-sz commented on entities/fraction_test.go
> +		Output [1]string
ok

2021-06-12 03:49 UTC, miraclesu approved these changes
LGTM. Thanks！

2021-06-12 03:50 UTC, merged